// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LotteryWithTickets$Type } from "./LotteryWithTickets";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LotteryWithTickets"]: LotteryWithTickets$Type;
    ["contracts/LotteryWithTickets.sol:LotteryWithTickets"]: LotteryWithTickets$Type;
  }

  interface ContractTypesMap {
    ["LotteryWithTickets"]: GetContractReturnType<LotteryWithTickets$Type["abi"]>;
    ["contracts/LotteryWithTickets.sol:LotteryWithTickets"]: GetContractReturnType<LotteryWithTickets$Type["abi"]>;
  }
}
